### ISSUE TITLE
pylitho training

### ISSUE THREAD

**Issue by thomashirtz** [OpenOPC/OpenILT#9]
Hello, I see that you are using some kernels for the experiments. Can I know how do you train the pylitho modules (which training script, ...) ?
I tried to search within the repository but I couldn't figure it out
Thanks!

**Comment by shelljane** [comment]
The pylitho models come from the ICCAD 13 mask optimization contest. We don't train them because they are physical models rather than machine learning models. If you are interested in machine learning models for lithography simulation, we may refer to another repo: shelljane/lithobench

**Comment by thomashirtz** [comment]
Ok, I understand
Thanks for your reply !
